name: 'Terraform Plan Apply'

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID:        ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET:    ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID:        ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (save to file)
        run: terraform plan -out=tfplan

      - name: Make plan readable
        run: terraform show -no-color tfplan > tfplan.txt

      - name: Upload plan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: |
            tfplan
            tfplan.txt
          retention-days: 7
          if-no-files-found: error

  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    env:
      ARM_CLIENT_ID:        ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET:    ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID:        ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: .

      - name: Terraform Apply (approved plan)
        run: terraform apply -input=false -auto-approve tfplan
